# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Moriarty-co
email: moriarty@moriarty-co.com
description: > # this means to ignore newlines until "baseurl:"
  This is home page of Moriarty corporation and its evil doings.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://moriarty-co.com" # the base hostname & protocol for your site
twitter_username: moriarty-co
github_username:  moriarty-co

# Build settings
markdown: kramdown
